### ISSUE TITLE
Crashes Sketch on 10.15 Catalina

### ISSUE THREAD

**Issue by greyskymedia** [lifeofmle/symbol-insert#2] opened 2019-10-09 01:25 UTC
Trying to trigger the insert plugin crashes Sketch. I just upgraded to 10.15.

**Comment by nicholas-evans** [comment] 2019-10-25 16:08
+1 It also crashed for me.

**Comment by lifeofmle** [comment] 2019-11-04 20:44
Thanks for raising this issue @greyskymedia @nicholas-evans I will try to resolve in next few days

**Comment by lifeofmle** [comment] 2019-11-10 13:24
This issue is now fixed with this release https://github.com/lifeofmle/symbol-insert/releases/tag/v1.2.1

The root cause was that there was a change with how Catalina handles webviews used for the popup screen

**Closed as completed** 2019-11-10 13:23 UTC
Labels: bug
